---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: Start Juniper Container
#      local_action: shell docker -d -t -p 5160:5160/udp -p 1883:1883 -i juniper/jnc /sbin/my_init -- bash -l
      docker:
        name: "{{ docker_name }}"
        image: "{{ docker_path }}/{{ docker_name }}"
        state: present
        pull: missing
      run_once: true
