underlay:
    local:
        asn: 60015
    neighbors:
## Leaf
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60016
        peer_ip: "{{ p2p.link5.2}}"
        local_ip: "{{ p2p.link5.1}}"
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60017
        peer_ip: "{{ p2p.link6.2}}"
        local_ip: "{{ p2p.link6.1}}"
      - interface: "{{ topo[inventory_hostname].port3.name }}"
        name: "{{ topo[inventory_hostname].port3.peer }}"
        asn: 60018
        peer_ip: "{{ p2p.link7.2}}"
        local_ip: "{{ p2p.link7.1}}"
#      - interface: "{{ topo[inventory_hostname].port4.name }}"
#        name: "{{ topo[inventory_hostname].port4.peer }}"
#        asn: 60019
#        peer_ip: "{{ p2p.link8.2}}"
#        local_ip: "{{ p2p.link8.1}}"
## Edge
      - interface: "{{ topo[inventory_hostname].port7.name }}"
        name: "{{ topo[inventory_hostname].port7.peer }}"
        asn: 60012
        peer_ip: "{{ p2p.link11.2}}"
        local_ip: "{{ p2p.link11.1}}"
      - interface: "{{ topo[inventory_hostname].port8.name }}"
        name: "{{ topo[inventory_hostname].port8.peer }}"
        asn: 60013
        peer_ip: "{{ p2p.link12.2}}"
        local_ip: "{{ p2p.link12.1}}"
