underlay:
    local:
        asn: 60012
    neighbors:
## Leaf
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60014
        peer_ip: "{{ p2p.link9.1}}"
        local_ip: "{{ p2p.link9.2}}"
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60015
        peer_ip: "{{ p2p.link11.1}}"
        local_ip: "{{ p2p.link11.2}}"
