underlay:
    local:
        asn: 60018
    neighbors:
## spine01
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60014
        peer_ip: "{{ p2p.link4.1}}"
        local_ip: "{{ p2p.link4.2}}"
## spine02
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60015
        peer_ip: "{{ p2p.link8.1}}"
        local_ip: "{{ p2p.link8.2}}"
