
# Global Variables used to generate the jvision part of the configuration
# these variables are mainly used in the template roles/jvision/templates/main.conf.j2
# please update these variable and the template as needed to match your environment
jti_collectors:
    default_collector:
      ip: 192.168.14.1
      port: 50000

jti_export_profiles:
    default_export_profile:
      # local_host: <ip>
      local_port: 1000
      reporting_rate: 10
      format: gpb
      transport: udp

jti_sensors:
    phy-interface:
        server: default_collector
        export_profile: default_export_profile
        resource: /junos/system/linecard/interface/
