underlay:
    local:
        asn: 60014
    neighbors:
## Leaf
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60016
        peer_ip: "{{ p2p.link1.2}}"
        local_ip: "{{ p2p.link1.1}}"
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60017
        peer_ip: "{{ p2p.link2.2}}"
        local_ip: "{{ p2p.link2.1}}"
      - interface: "{{ topo[inventory_hostname].port3.name }}"
        name: "{{ topo[inventory_hostname].port3.peer }}"
        asn: 60018
        peer_ip: "{{ p2p.link3.2}}"
        local_ip: "{{ p2p.link3.1}}"
#      - interface: "{{ topo[inventory_hostname].port4.name }}"
#        name: "{{ topo[inventory_hostname].port4.peer }}"
#        asn: 60019
#        peer_ip: "{{ p2p.link4.2}}"
#        local_ip: "{{ p2p.link4.1}}"
## Edge
      - interface: "{{ topo[inventory_hostname].port7.name }}"
        name: "{{ topo[inventory_hostname].port7.peer }}"
        asn: 60012
        peer_ip: "{{ p2p.link9.2}}"
        local_ip: "{{ p2p.link9.1}}"
      - interface: "{{ topo[inventory_hostname].port8.name }}"
        name: "{{ topo[inventory_hostname].port8.peer }}"
        asn: 60013
        peer_ip: "{{ p2p.link10.2}}"
        local_ip: "{{ p2p.link10.1}}"
